# 日志相关

# 日志级别
console_log_level: "INFO"
file_log_level: "DEBUG"
# 日志格式
console_log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file_log_format: "%(asctime)s - %(name)s - %(levelname)s - [%(classname)s] - %(message)s"
# 日志最大文件大小（单位：MB）
file_log_max_size: 100
# 日志最大文件数量
file_log_max_files: 10